// apps/react/src/components/Button.tsx
import { Button, Space } from '@arco-design/web-react';
import { useState } from 'react';

interface ButtonProps {
  onEvent?: (message: string) => void;
}

function ButtonComponent({ onEvent }: ButtonProps) {
  const [count, setCount] = useState(0);

  return (
    <Space direction="vertical">
      <Button
        type="primary"
        onClick={() => {
          const next = count + 1;
          setCount(next);
          onEvent?.(`按钮被点击 ${next} 次`);
        }}
      >
        点击计数：{count}
      </Button>
    </Space>
  );
}

export default ButtonComponent;

// apps/vue/src/components/Button.tsx
import { Button, Space } from '@arco-design/web-vue';
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'Button',
  props: {
    onEvent: {
      type: Function as unknown as () => ((message: string) => void) | undefined,
      default: undefined,
    },
  },
  setup(props) {
    const count = ref(0);

    const onButtonClick = () => {
      count.value += 1;
      props.onEvent?.(`按钮被点击 ${count.value} 次`);
    };

    return () => (
      <Space direction="vertical">
        <Button type="primary" onClick={onButtonClick}>
          点击计数：{count.value}
        </Button>
      </Space>
    );
  },
});
