// apps/react/src/components/Form.tsx
import { Input, Space, Typography } from '@arco-design/web-react';
import { useState } from 'react';

interface FormProps {
  onEvent?: (message: string) => void;
}

function FormComponent({ onEvent }: FormProps) {
  const [text, setText] = useState('');

  return (
    <Space direction="vertical" style={{ width: '100%' }}>
      <Input
        value={text}
        placeholder="输入任意内容"
        onChange={(value) => {
          setText(value);
          onEvent?.(`输入值变更：${value || '(空)'}`);
        }}
      />
      <Typography.Text>当前输入：{text || '(空)'}</Typography.Text>
    </Space>
  );
}

export default FormComponent;

// apps/vue/src/components/Form.tsx
import { Input, Space, TypographyText } from '@arco-design/web-vue';
import { defineComponent, ref } from 'vue';

export default defineComponent({
  name: 'Form',
  props: {
    onEvent: {
      type: Function as unknown as () => ((message: string) => void) | undefined,
      default: undefined,
    },
  },
  setup(props) {
    const text = ref('');

    const onInputValue = (value: string) => {
      text.value = value;
      props.onEvent?.(`输入值变更：${value || '(空)'}`);
    };

    return () => (
      <Space direction="vertical" fill>
        <Input
          modelValue={text.value}
          placeholder="输入任意内容"
          onUpdate:modelValue={(value: string) => onInputValue(value)}
        />
        <TypographyText>{`当前输入：${text.value || '(空)'}`}</TypographyText>
      </Space>
    );
  },
});
