// docs/apps/vue/src/App.tsx
import { defineComponent } from 'vue';
import Literal from './components/Literal.vue';
import Widget from './components/Widget.vue';

type FrameworkKind = 'react' | 'vue';

export default defineComponent({
  name: 'VueTsxDemo',
  props: {
    exampleId: {
      type: String,
      default: '',
    },
    onEvent: {
      type: Function as unknown as () => ((payload: { framework: FrameworkKind; message: string }) => void) | undefined,
      default: undefined,
    },
  },
  setup(props) {
    const demoRenderMap = {
      'literal': () => <Literal />,
      'widget': () => <Widget />,
    };

    const renderCurrentDemo = () => {
      const renderer =
        demoRenderMap[props.exampleId as keyof typeof demoRenderMap] ?? demoRenderMap['literal'];
      return renderer();
    };

    return () => (
      renderCurrentDemo()
    );
  },
});

// docs/apps/react/src/App.tsx
import '@arco-design/web-react/dist/css/arco.css';
import Literal from './components/Literal.tsx';
import Widget from './components/Widget.tsx';

interface AppProps {
  exampleId?: string;
  onEvent?: (message: string) => void;
}

function App({ exampleId = '' }: AppProps) {
  const demoRenderMap = {
    'literal': () => <Literal />,
    'widget': () => <Widget />,
  };

  const renderCurrentDemo = () => {
    const renderer =
      demoRenderMap[exampleId as keyof typeof demoRenderMap] ?? demoRenderMap['literal'];
    return renderer();
  };

  return (
    renderCurrentDemo()
  );
}

export default App;
